version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    docker:
      image: circleci/node:10.16.3 # ...with this image as the primary container; this is where all `steps` will run
      image: mongo:3.4.4-jessie
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      environment:
        MONGO_URL: "mongodb://localhost:27017/livepoetrytest"
workflows:
    build-and-test:
      jobs:
        - build-and-test
