version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      - image: circleci/node:12.16-buster
      - image: circleci/mongo:4.0.6
    steps:
      - checkout
      - run:
          name: install-packages
          command: npm install
      - run:
          name: test
          command: npm test
